spring:
  security:
    user:
      name: jilinwula
      password: jilinwula.com
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    cache: false
    suffix: .html
    encoding: UTF-8
    content-type: text/html
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/security?zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: jilinwula
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true